2023-06-20 23:20:03,911 - ERROR - Error booking ticket for user admin
Traceback (most recent call last):
  File "C:\Users\Matheus\Desktop\Coding\flight_booking_system\flight_booking\views.py", line 92, in book_ticket
    booking = Booking.objects.create(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\query.py", line 656, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\fields\related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "<SimpleLazyObject: <User: admin>>": "Booking.user" must be a "User" instance.
2023-06-20 23:20:10,766 - ERROR - Error booking ticket for user admin
Traceback (most recent call last):
  File "C:\Users\Matheus\Desktop\Coding\flight_booking_system\flight_booking\views.py", line 92, in book_ticket
    booking = Booking.objects.create(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\query.py", line 656, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\fields\related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "<SimpleLazyObject: <User: admin>>": "Booking.user" must be a "User" instance.
2023-06-20 23:22:04,727 - ERROR - Error booking ticket for user admin
Traceback (most recent call last):
  File "C:\Users\Matheus\Desktop\Coding\flight_booking_system\flight_booking\views.py", line 92, in book_ticket
    booking = Booking.objects.create(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\query.py", line 656, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\fields\related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "<SimpleLazyObject: <User: admin>>": "Booking.user" must be a "User" instance.
2023-06-20 23:27:07,665 - ERROR - Error booking ticket for user admin
Traceback (most recent call last):
  File "C:\Users\Matheus\Desktop\Coding\flight_booking_system\flight_booking\views.py", line 92, in book_ticket
    booking = Booking.objects.create(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\query.py", line 656, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\fields\related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "<SimpleLazyObject: <User: admin>>": "Booking.user" must be a "User" instance.
2023-06-20 23:29:30,748 - ERROR - Error booking ticket for user admin
Traceback (most recent call last):
  File "C:\Users\Matheus\Desktop\Coding\flight_booking_system\flight_booking\views.py", line 92, in book_ticket
    booking = Booking(
              ^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\fields\related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "<SimpleLazyObject: <User: admin>>": "Booking.user" must be a "User" instance.
2023-06-20 23:31:31,491 - ERROR - Error booking ticket for user admin
Traceback (most recent call last):
  File "C:\Users\Matheus\Desktop\Coding\flight_booking_system\flight_booking\views.py", line 95, in book_ticket
    booking = Booking(
              ^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\fields\related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "<User: admin>": "Booking.user" must be a "User" instance.
2023-06-20 23:34:17,720 - ERROR - Error booking ticket for user admin
Traceback (most recent call last):
  File "C:\Users\Matheus\Desktop\Coding\flight_booking_system\flight_booking\views.py", line 96, in book_ticket
    booking = Booking(
              ^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\fields\related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "<User: admin>": "Booking.user" must be a "User" instance.
2023-06-21 08:10:55,262 - ERROR - Error booking ticket for user admin
Traceback (most recent call last):
  File "C:\Users\Matheus\Desktop\Coding\flight_booking_system\flight_booking\views.py", line 101, in book_ticket
    booking = Booking(
              ^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\fields\related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "<User: admin>": "Booking.user" must be a "User" instance.
2023-06-21 08:15:19,121 - ERROR - Error booking ticket for user admin
Traceback (most recent call last):
  File "C:\Users\Matheus\Desktop\Coding\flight_booking_system\flight_booking\views.py", line 101, in book_ticket
    booking = Booking(
              ^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\fields\related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "<User: admin>": "Booking.user" must be a "User" instance.
2023-06-21 08:18:09,034 - ERROR - Error booking ticket for user admin
Traceback (most recent call last):
  File "C:\Users\Matheus\Desktop\Coding\flight_booking_system\flight_booking\views.py", line 96, in book_ticket
    booking = Booking(
              ^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\fields\related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "<SimpleLazyObject: <User: admin>>": "Booking.user" must be a "User" instance.
2023-06-21 08:20:22,664 - ERROR - Error booking ticket for user admin
Traceback (most recent call last):
  File "C:\Users\Matheus\Desktop\Coding\flight_booking_system\flight_booking\views.py", line 96, in book_ticket
    booking = Booking(
              ^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\fields\related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "<User: admin>": "Booking.user" must be a "User" instance.
2023-06-21 08:22:25,153 - ERROR - Error booking ticket for user admin
Traceback (most recent call last):
  File "C:\Users\Matheus\Desktop\Coding\flight_booking_system\flight_booking\views.py", line 96, in book_ticket
    booking = Booking(
              ^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\fields\related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "<User: admin>": "Booking.user" must be a "User" instance.
2023-06-21 08:28:05,352 - ERROR - Error booking ticket for user admin
Traceback (most recent call last):
  File "C:\Users\Matheus\Desktop\Coding\flight_booking_system\flight_booking\views.py", line 96, in book_ticket
    booking = Booking(
              ^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\fields\related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "<bound method QuerySet.get of <django.contrib.auth.models.UserManager object at 0x000002A880A2E010>>": "Booking.user" must be a "User" instance.
2023-06-21 08:28:11,009 - ERROR - Error booking ticket for user admin
Traceback (most recent call last):
  File "C:\Users\Matheus\Desktop\Coding\flight_booking_system\flight_booking\views.py", line 96, in book_ticket
    booking = Booking(
              ^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\fields\related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "<bound method QuerySet.get of <django.contrib.auth.models.UserManager object at 0x000002A880A2E010>>": "Booking.user" must be a "User" instance.
2023-06-21 08:35:18,039 - ERROR - Error booking ticket for user admin
Traceback (most recent call last):
  File "C:\Users\Matheus\Desktop\Coding\flight_booking_system\flight_booking\views.py", line 96, in book_ticket
    booking = Booking(
              ^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\fields\related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "<SimpleLazyObject: <User: admin>>": "Booking.user" must be a "User" instance.
2023-06-21 08:37:43,003 - ERROR - Error booking ticket for user admin
Traceback (most recent call last):
  File "C:\Users\Matheus\Desktop\Coding\flight_booking_system\flight_booking\views.py", line 96, in book_ticket
    booking = Booking(
              ^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\fields\related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "<SimpleLazyObject: <User: admin>>": "Booking.user" must be a "User" instance.
2023-06-21 08:41:58,027 - ERROR - Error booking ticket for user admin
Traceback (most recent call last):
  File "C:\Users\Matheus\Desktop\Coding\flight_booking_system\flight_booking\views.py", line 103, in book_ticket
    discounted_price_economy = apply_discount('Economy Class', total_price_economy)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\Desktop\Coding\flight_booking_system\flight_booking\views.py", line 172, in apply_discount
    return ticket_price * 0.8
           ~~~~~~~~~~~~~^~~~~
TypeError: unsupported operand type(s) for *: 'decimal.Decimal' and 'float'
2023-06-21 08:43:38,876 - ERROR - Error booking ticket for user admin
Traceback (most recent call last):
  File "C:\Users\Matheus\Desktop\Coding\flight_booking_system\flight_booking\views.py", line 103, in book_ticket
    discounted_price_economy = apply_discount('Economy Class', total_price_economy)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\Desktop\Coding\flight_booking_system\flight_booking\views.py", line 172, in apply_discount
    return ticket_price * 0.85
           ~~~~~~~~~~~~~^~~~~~
TypeError: unsupported operand type(s) for *: 'decimal.Decimal' and 'float'
2023-06-21 08:44:46,140 - ERROR - Error booking ticket for user admin
Traceback (most recent call last):
  File "C:\Users\Matheus\Desktop\Coding\flight_booking_system\flight_booking\views.py", line 118, in book_ticket
    booking_economy = Booking.objects.create(
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\query.py", line 656, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\fields\related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "<SimpleLazyObject: <User: admin>>": "Booking.user" must be a "User" instance.
2023-06-21 08:48:29,024 - ERROR - Error booking ticket for user admin
Traceback (most recent call last):
  File "C:\Users\Matheus\Desktop\Coding\flight_booking_system\flight_booking\views.py", line 121, in book_ticket
    booking_economy = Booking.objects.create(
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\query.py", line 656, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\fields\related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "<User: admin>": "Booking.user" must be a "User" instance.
2023-06-21 08:51:00,353 - ERROR - Error booking ticket for user admin
Traceback (most recent call last):
  File "C:\Users\Matheus\Desktop\Coding\flight_booking_system\flight_booking\views.py", line 120, in book_ticket
    booking_economy = Booking.objects.create(
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\query.py", line 656, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\fields\related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "<SimpleLazyObject: <User: admin>>": "Booking.user" must be a "User" instance.
2023-06-21 08:53:20,190 - ERROR - Error booking ticket for user admin
Traceback (most recent call last):
  File "C:\Users\Matheus\Desktop\Coding\flight_booking_system\flight_booking\views.py", line 120, in book_ticket
    booking_economy = Booking(
                      ^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\fields\related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "<SimpleLazyObject: <User: admin>>": "Booking.user" must be a "User" instance.
2023-06-21 08:59:40,703 - ERROR - Error booking ticket for user admin
Traceback (most recent call last):
  File "C:\Users\Matheus\Desktop\Coding\flight_booking_system\flight_booking\views.py", line 120, in book_ticket
    booking_economy = Booking(
                      ^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\fields\related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "<class 'django.contrib.auth.models.User'>": "Booking.user" must be a "User" instance.
2023-06-21 09:06:04,858 - ERROR - Error booking ticket for user admin
Traceback (most recent call last):
  File "C:\Users\Matheus\Desktop\Coding\flight_booking_system\flight_booking\views.py", line 120, in book_ticket
    booking = Booking(
              ^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\fields\related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "<class 'django.contrib.auth.models.User'>": "Booking.user" must be a "User" instance.
2023-06-21 09:09:28,090 - ERROR - Error booking ticket for user admin
Traceback (most recent call last):
  File "C:\Users\Matheus\Desktop\Coding\flight_booking_system\flight_booking\views.py", line 117, in book_ticket
    booking_economy = Booking(
                      ^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\fields\related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "<SimpleLazyObject: <User: admin>>": "Booking.user" must be a "User" instance.
2023-06-21 09:09:58,697 - ERROR - Error booking ticket for user admin
Traceback (most recent call last):
  File "C:\Users\Matheus\Desktop\Coding\flight_booking_system\flight_booking\views.py", line 117, in book_ticket
    booking_economy = Booking(
                      ^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\fields\related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "<SimpleLazyObject: <User: admin>>": "Booking.user" must be a "User" instance.
2023-06-21 09:11:13,403 - ERROR - Error booking ticket for user admin
Traceback (most recent call last):
  File "C:\Users\Matheus\Desktop\Coding\flight_booking_system\flight_booking\views.py", line 117, in book_ticket
    booking_economy = Booking(
                      ^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\fields\related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "<SimpleLazyObject: <User: admin>>": "Booking.user" must be a "User" instance.
2023-06-21 09:14:54,607 - ERROR - Error booking ticket for user admin
Traceback (most recent call last):
  File "C:\Users\Matheus\Desktop\Coding\flight_booking_system\flight_booking\views.py", line 117, in book_ticket
    booking = Booking.objects.create(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\query.py", line 656, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\fields\related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "<SimpleLazyObject: <User: admin>>": "Booking.user" must be a "User" instance.
2023-06-21 09:16:21,541 - ERROR - Error booking ticket for user admin
Traceback (most recent call last):
  File "C:\Users\Matheus\Desktop\Coding\flight_booking_system\flight_booking\views.py", line 117, in book_ticket
    booking = Booking.objects.create(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\query.py", line 656, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: Booking() got unexpected keyword arguments: 'username'
2023-06-21 09:16:49,205 - ERROR - Error booking ticket for user admin
Traceback (most recent call last):
  File "C:\Users\Matheus\Desktop\Coding\flight_booking_system\flight_booking\views.py", line 117, in book_ticket
    booking = Booking.objects.create(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\query.py", line 656, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\fields\related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "2": "Booking.user" must be a "User" instance.
2023-06-21 09:17:30,927 - ERROR - Error booking ticket for user admin
Traceback (most recent call last):
  File "C:\Users\Matheus\Desktop\Coding\flight_booking_system\flight_booking\views.py", line 117, in book_ticket
    booking = Booking.objects.create(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\query.py", line 656, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\fields\related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "2": "Booking.user" must be a "User" instance.
2023-06-21 09:18:36,913 - ERROR - Error booking ticket for user admin
Traceback (most recent call last):
  File "C:\Users\Matheus\Desktop\Coding\flight_booking_system\flight_booking\views.py", line 117, in book_ticket
    booking = Booking.objects.create(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\query.py", line 656, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\fields\related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "<SimpleLazyObject: <User: admin>>": "Booking.user" must be a "User" instance.
2023-06-21 09:20:48,466 - ERROR - Error booking ticket for user admin
Traceback (most recent call last):
  File "C:\Users\Matheus\Desktop\Coding\flight_booking_system\flight_booking\views.py", line 117, in book_ticket
    booking = Booking.objects.create(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\query.py", line 656, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\fields\related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "<User: admin>": "Booking.user" must be a "User" instance.
2023-06-21 09:23:14,737 - ERROR - Error booking ticket for user admin
Traceback (most recent call last):
  File "C:\Users\Matheus\Desktop\Coding\flight_booking_system\flight_booking\views.py", line 117, in book_ticket
    booking = Booking.objects.create(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\query.py", line 656, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\fields\related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "<User: admin>": "Booking.user" must be a "User" instance.
2023-06-21 10:16:30,098 - ERROR - Error booking ticket for user admin
Traceback (most recent call last):
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
          ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1048, "Column 'user_id' cannot be null")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Matheus\Desktop\Coding\flight_booking_system\flight_booking\views.py", line 116, in book_ticket
    booking = Booking.objects.create(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\debug_toolbar\panels\sql\tracking.py", line 246, in execute
    return self._record(super().execute, sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\debug_toolbar\panels\sql\tracking.py", line 167, in _record
    return method(sql, params)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\backends\mysql\base.py", line 80, in execute
    raise IntegrityError(*tuple(e.args))
django.db.utils.IntegrityError: (1048, "Column 'user_id' cannot be null")
2023-06-21 10:19:23,723 - ERROR - Error booking ticket for user admin
Traceback (most recent call last):
  File "C:\Users\Matheus\Desktop\Coding\flight_booking_system\flight_booking\views.py", line 120, in book_ticket
    booking = Booking.objects.create(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\query.py", line 656, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\fields\related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "<User: admin>": "Booking.user" must be a "User" instance.
2023-06-21 10:20:18,018 - ERROR - Error booking ticket for user admin
Traceback (most recent call last):
  File "C:\Users\Matheus\Desktop\Coding\flight_booking_system\flight_booking\views.py", line 116, in book_ticket
    booking = Booking.objects.create(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\query.py", line 656, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\fields\related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "<User: admin>": "Booking.user" must be a "User" instance.
2023-06-21 10:21:30,529 - ERROR - Error booking ticket for user admin
Traceback (most recent call last):
  File "C:\Users\Matheus\Desktop\Coding\flight_booking_system\flight_booking\views.py", line 116, in book_ticket
    user_instance = user if created else user[0]
                                       ~~~~^^^
TypeError: 'User' object is not subscriptable
2023-06-21 10:23:03,276 - ERROR - Error booking ticket for user admin
Traceback (most recent call last):
  File "C:\Users\Matheus\Desktop\Coding\flight_booking_system\flight_booking\views.py", line 133, in book_ticket
    booking.ticket = ticket_economy
    ^^^^^^^
UnboundLocalError: cannot access local variable 'booking' where it is not associated with a value
2023-06-21 10:25:19,867 - ERROR - Error booking ticket for user admin
Traceback (most recent call last):
  File "C:\Users\Matheus\Desktop\Coding\flight_booking_system\flight_booking\views.py", line 135, in book_ticket
    booking.ticket = ticket_economy
    ^^^^^^^
UnboundLocalError: cannot access local variable 'booking' where it is not associated with a value
2023-06-21 10:29:09,543 - ERROR - Error booking ticket for user admin
Traceback (most recent call last):
  File "C:\Users\Matheus\Desktop\Coding\flight_booking_system\flight_booking\views.py", line 113, in book_ticket
    booking_economy = Booking.objects.create(
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\query.py", line 656, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\fields\related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "<User: admin>": "Booking.user" must be a "User" instance.
2023-06-21 10:38:13,337 - ERROR - Error booking ticket for user admin
Traceback (most recent call last):
  File "C:\Users\Matheus\Desktop\Coding\flight_booking_system\flight_booking\views.py", line 98, in book_ticket
    discounted_price = apply_discount(num_tickets_total, total_price)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\Desktop\Coding\flight_booking_system\flight_booking\views.py", line 168, in apply_discount
    discounted_price = ticket_price - (ticket_price * discount)
                                       ~~~~~~~~~~~~~^~~~~~~~~~
TypeError: unsupported operand type(s) for *: 'decimal.Decimal' and 'float'
2023-06-21 12:27:01,976 - ERROR - Error booking ticket for user admin
Traceback (most recent call last):
  File "C:\Users\Matheus\Desktop\Coding\flight_booking_system\flight_booking\views.py", line 107, in book_ticket
    booking = Booking.objects.create(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\query.py", line 656, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\fields\related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "<User: admin>": "Booking.user" must be a "User" instance.
2023-06-21 12:28:10,576 - ERROR - Error booking ticket for user admin
Traceback (most recent call last):
  File "C:\Users\Matheus\Desktop\Coding\flight_booking_system\flight_booking\views.py", line 107, in book_ticket
    booking = Booking.objects.create(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\query.py", line 656, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\fields\related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "<User: masantosks>": "Booking.user" must be a "User" instance.
2023-06-21 12:36:44,316 - ERROR - Error booking ticket for user admin
Traceback (most recent call last):
  File "C:\Users\Matheus\Desktop\Coding\flight_booking_system\flight_booking\views.py", line 105, in book_ticket
    booking = Booking.objects.create(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\query.py", line 656, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\fields\related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "<User: admin>": "Booking.user" must be a "User" instance.
2023-06-21 12:39:50,423 - ERROR - Error booking ticket for user admin
Traceback (most recent call last):
  File "C:\Users\Matheus\Desktop\Coding\flight_booking_system\flight_booking\views.py", line 105, in book_ticket
    booking = Booking.objects.create(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\query.py", line 656, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\fields\related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "<SimpleLazyObject: <User: admin>>": "Booking.user" must be a "User" instance.
2023-06-21 12:39:59,410 - ERROR - Error booking ticket for user admin
Traceback (most recent call last):
  File "C:\Users\Matheus\Desktop\Coding\flight_booking_system\flight_booking\views.py", line 105, in book_ticket
    booking = Booking.objects.create(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\query.py", line 656, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\fields\related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "<SimpleLazyObject: <User: admin>>": "Booking.user" must be a "User" instance.
2023-06-21 12:41:52,832 - ERROR - Error booking ticket for user admin
Traceback (most recent call last):
  File "C:\Users\Matheus\Desktop\Coding\flight_booking_system\flight_booking\views.py", line 107, in book_ticket
    booking = Booking.objects.create(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\query.py", line 656, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\fields\related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "<User: admin>": "Booking.user" must be a "User" instance.
2023-06-21 12:43:09,613 - ERROR - Error booking ticket for user admin
Traceback (most recent call last):
  File "C:\Users\Matheus\Desktop\Coding\flight_booking_system\flight_booking\views.py", line 107, in book_ticket
    booking = Booking.objects.create(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\query.py", line 656, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\Matheus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\db\models\fields\related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "<User: admin>": "Booking.user" must be a "User" instance.
